### ISSUE TITLE
npm install 安装依赖失败，readme不够详细啊

### ISSUE THREAD

**Issue by MaloneGod** [sherylynn/pdf-sync#1]
npm WARN tar ENOENT: no such file or directory, open '/home/ubuntu/pdf-sync/node_modules/.staging/string-width-f89de119/package.json'
npm WARN tar ENOENT: no such file or directory, open '/home/ubuntu/pdf-sync/node_modules/.staging/string-width-f89de119/index.js'
npm WARN tar ENOENT: no such file or directory, open '/home/ubuntu/pdf-sync/node_modules/.staging/string-width-f89de119/license'
npm WARN tar ENOENT: no such file or directory, open '/home/ubuntu/pdf-sync/node_modules/.staging/string-width-f89de119/readme.md'
npm WARN tar ENOENT: no such file or directory, open '/home/ubuntu/pdf-sync/node_modules/.staging/handlebars-42da7ae7/dist/amd/handlebars/decorators/inline.js'
npm WARN tar ENOENT: no such file or directory, lstat '/home/ubuntu/pdf-sync/node_modules/.staging/leveldown-d1fb8ba2/deps/snappy/snappy-1.1.4/m4'
npm WARN tar ENOENT: no such file or directory, open '/home/ubuntu/pdf-sync/node_modules/.staging/leveldown-d1fb8ba2/deps/snappy/snappy-1.1.4/Makefile.am'
npm WARN tar ENOENT: no such file or directory, open '/home/ubuntu/pdf-sync/node_modules/.staging/leveldown-d1fb8ba2/deps/snappy/snappy-1.1.4/Makefile.in'
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/event-stream/-/event-stream-3.3.6.tgz
npm ERR! 404
npm ERR! 404  'event-stream@3.3.6' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'pdf-sync'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-13T01_55_06_369Z-debug.log

**Comment by sherylynn** [comment]
just delete package-lock.json then u will succes . I will update as soon as possible
删掉package-lock.json 就可以安装成功, 我迟点提交一个更新

**Comment by sherylynn** [comment]
fixed it
